name: ${COMPOSE_PROJECT_NAME:-mcp-lab}

include:
  # API
  - path: api/contract/compose.yml
    env_file: .env

  # Datastores
  - path: datastores/sqlserver/compose.yml
    env_file: .env
  - path: datastores/oracle/compose.yml
    env_file: .env
  - path: datastores/elastic/compose.yml
    env_file: .env
  - path: datastores/redis/compose.yml
    env_file: .env

  # Identity
  - path: identity/oidc/compose.yml
    env_file: .env

  # Messaging
  - path: messaging/mosquitto/compose.yml
    env_file: .env
  - path: messaging/rabbitmq/compose.yml
    env_file: .env

  # Documents
  - path: documents/reader/compose.yml
    env_file: .env

  # System
  - path: system/docker/compose.yml
    env_file: .env

  # Tools
  - path: tools/mailpit/compose.yml
    env_file: .env

networks:
  shared_net:
    name: ${COMPOSE_PROJECT_NAME:-mcp-lab}_shared_net
